gui:
  branchColors:
    'docs': '#11aaff' # use a light blue for branches beginning with 'docs/'
    'feature': '#20bd47'
    'hotfix': '#b03f3f'
    'chore:': '#fa9025'
  showIcons: true
os:
  editCommand: 'nvim'
  editCommandTemplate: '{{editor}} +{{line}} -- {{filename}}'
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
  commitPrefixes:
    destiny-data-synchronizer: # This is repository folder name
      pattern: "^(\\w+)\\/(\\w+-\\w+).*"
      replace: '$1: $2: '
    spock: # This is repository folder name
      pattern: "^(\\w+)\\/(\\w+-\\w+).*"
      replace: '$1: $2: '
services:
  'code.moba.live': 'gitlab:code.moba.live'
