#!/usr/bin/env bash

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# ====== Variables =============================

gaps_top="4"
gaps_bottom="4"
gaps_left="4"
gaps_right="4"
gaps_inner="4"

normal_border_color="010101"
focused_border_color="808080"
preselect_border_color="2d74da"

# ====== Tiling settings =======================

yabai -m config layout                      bsp

yabai -m config top_padding                 "${gaps_top}"
yabai -m config bottom_padding              "${gaps_bottom}"
yabai -m config left_padding                "${gaps_left}"
yabai -m config right_padding               "${gaps_right}"
yabai -m config window_gap                  "${gaps_inner}"

yabai -m config mouse_follows_focus         off
yabai -m config focus_follows_mouse         off

yabai -m config mouse_modifier              fn
yabai -m config mouse_action1               move
yabai -m config mouse_action2               resize

yabai -m config window_topmost              off
yabai -m config window_opacity              off
yabai -m config window_shadow               float

yabai -m config active_window_opacity       0.9
yabai -m config normal_window_opacity       0.8
yabai -m config split_ratio                 0.5
yabai -m config auto_balance                off

# ====== Border settings =======================

yabai -m config window_border               off
yabai -m config window_border_width         2
yabai -m config active_window_border_color  "0xE0${focused_border_color}"
yabai -m config normal_window_border_color  "0x00${normal_border_color}"

# ====== Desktop labels =========================
yabai -m space 1 --label code
yabai -m space 2 --label web
yabai -m space 3 --label mail
yabai -m space 4 --label media
yabai -m space 5 --label games

yabai -m config --space mail  layout        stack
yabai -m config --space games layout        float

# ====== List of rules =========================
yabai -m rule --add app="^Mail$" space=mail
yabai -m rule --add app="^Safari$" space=web
yabai -m rule --add app="^Transmission$" space=media
yabai -m rule --add app="^Spotify$" space=media
yabai -m rule --add app="^Discord$" space=social grid=1:1:0:0:1:1 manage=off
yabai -m rule --add app="^Steam$" space=media manage=off
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^App Store$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^1Password 7$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Dictionary$" manage=off
yabai -m rule --add app="^Keka$" manage=off
yabai -m rule --add app="^Transmission$" manage=off

yabai -m rule --add app="^Code$" opacity=0.9
